name: Autograding
on: [push]  # Run when a student pushes code to their fork

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3  # Get the student’s code

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run the student’s script
        run: python group_by_script.py  # Adjust if your script has a different name

      - name: Check if `results.csv` exists
        run: |
          if [ -f "results.csv" ]; then
            echo "results.csv exists"
          else
            echo "Error: results.csv not found"
            exit 1
          fi

      - name: Clone the private test data repo
        env:
          PAT: ${{ secrets.TEST_DATA_PAT }}  # Use the stored PAT
        run: |
          git clone https://github.com/hans-r7/is640pythonorg-classroom-test-data.git test-data

      - name: Compare results with expected output
        run: |
          python -c "
          import pandas as pd
          student_result = pd.read_csv('results.csv')
          expected_result = pd.read_csv('test-data/expected_answer.csv')
          assert student_result.equals(expected_result), 'Output does not match expected!'
          print('All tests passed!')
          "

      - name: Clean up (optional)
        run: rm -rf test-data  # Remove the private repo after testing
