name: Autograding
on: [push]

jobs:
  autograding:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run student script
        run: python group_by_script.py

      - name: Check if results.csv exists
        run: |
          if [ -f "results.csv" ]; then
            echo "results.csv exists"
          else
            echo "Error: results.csv does not exist"
            exit 1
          fi

      - name: Compare results.csv with expected output
        run: |
          python -c "
          import pandas as pd
          result = pd.read_csv('results.csv')
          expected = pd.read_csv('expected_answer.csv')
          assert result.equals(expected), 'The output does not match the expected result'
          print('All tests passed!')
          "